name = "littlebopeep"
main = ".open-next/worker.js"
compatibility_date = "2026-03-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_APP_URL = "https://littlebopeep.chris-bee.workers.dev"
NEXT_PUBLIC_VAPID_PUBLIC_KEY = "BDAzYME9gvafPBIJff16_dkEOYdREZdPA6gdIUL6wA76mUY2-IiFlzXhV1x-dPfek36GZ6FPvW6D72NXXpfVXTE"
VAPID_SUBJECT = "info@littlebopeep.app"
